version: '3.4'

services:
  bookify.api:
    image: ${DOCKER_REGISTRY-}bookifyapi
    container_name: Bookify.Api
    ports:
      - "8080:8080"
      - "8081:8081"
    build:
      context: .
      dockerfile: Bookify.Api/Dockerfile
#    links:
#      - bookify-idp
    networks:
      - "backend"
    depends_on:
     - bookify-db

  bookify-db:
    container_name: Bookify.Db
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=bookify
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - "backend"
    ports:
      - "5432:5432"
    volumes:
      - ./.containers/database:/var/lib/postgresql/data
  
  bookify-idp:
    image: quay.io/keycloak/keycloak:latest
    container_name: "Bookify.identity"
    command: start-dev --import-realm
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./.containers/identity:/opt/keycloak/data
      - ./.files/bookify-realm-export.json:/opt/keycloak/data/import/realm.json
    networks:
      backend:
        aliases:
          - "bookify-idp"
    ports:
      - "18080:8080"

  bookify-seq:
    image: datalust/seq:latest
    container_name: Bookify.Seq
    environment:
      - ACCEPT_EULA=Y
    networks:
      backend:
        aliases:
        - "bookify-seq"
    ports:
      - 5341:5341
      - 8082:80
  
networks:
  backend:
    driver: bridge
      
